### ISSUE TITLE
blsagg service doesn't returned sorted operator pubkeys

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigensdk-go#187]
**Describe the bug**

checkSignatures [expects nonsigner operator pubkeys to be sorted](https://github.com/Layr-Labs/eigenlayer-middleware/blob/dev/src/BLSSignatureChecker.sol#L149), but the blsagg service currently doesn't sort operator pubkeys. See https://github.com/Layr-Labs/eigensdk-go/blob/977516719b1a7b6ec00901175f49e0ead6c4917c/services/bls_aggregation/blsagg.go#L403

**To Reproduce**
Don't have a reproducible test right now. This was raised by an avs team. Will need to add a test case for this.

**Comment by i9** [comment]
thanks! we hope this will also fixed undetermined order of nonSignersOperatorIds and NonSignersPubkeysG1 (due to golang map iter random order)

**Comment by samlaf** [comment]
Fixed in #188
