### ISSUE TITLE
smart contract bindings should only be of interfaces

### ISSUE THREAD

**Issue by shrimalmadhur** [Layr-Labs/eigensdk-go#194]
**Is your feature request related to a problem? Please describe.**
Right now smart contract bindings have a lot of implementation bindings (and some interface bindings like `ISlasher`. Ideally we should only have Interfaces bindings so that we don't need to update bindings whenever contract implementation changes

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by 0xpanicError** [comment]
Can I take this one? 

cc @samlaf

**Comment by shrimalmadhur** [comment]
I think we want to keep it all implementation since - Interfaces are very specific to solidity and we want to keep it up to date with impl. Closing this now.
