### ISSUE TITLE
Add an option for ```NewOperatorsInfoServiceInMemory``` to start scanning from a given block

### ISSUE THREAD

**Issue by MauroToscano** [Layr-Labs/eigensdk-go#259]
```NewOperatorsInfoServiceInMemory``` takes too much time to initialize.

It could start scanning the blockchain from some arbitrary block. ```QueryExistingRegisteredOperatorPubKeys``` already provides that option.

**Comment by samlaf** [comment]
Hey @MauroToscano sorry forgot to answer this.

This is definitely needed. I already added startBlock params to the avsreader methods: https://github.com/Layr-Labs/eigensdk-go/blob/4b1bb2a86e2acc0de02952b5a20de1aa5eaaf746/chainio/clients/avsregistry/reader.go#L76

Would just need to update the call to them in the blsagg service: https://github.com/Layr-Labs/eigensdk-go/blob/4b1bb2a86e2acc0de02952b5a20de1aa5eaaf746/services/operatorsinfo/operatorsinfo_inmemory.go#L180 that is currently passing nil (aka start from block 0).
