### ISSUE TITLE
Feat(blsagg): use block-based expiry instead of time-based

### ISSUE THREAD

**Issue by samlaf** [Layr-Labs/eigensdk-go#300]
**Is your feature request related to a problem? Please describe.**

bls signature verification gas costs are linear in the # of non signers, so the fewer nonsigners, the cheaper the verification gas costs. Right now the API for the blsagg service to return an aggregate signature has 2 dofs:
- minimum signed stake threshold (60%, 80%, etc.)
- time to expiry  (see this [TODO](https://github.com/Layr-Labs/eigensdk-go/blob/4b1bb2a86e2acc0de02952b5a20de1aa5eaaf746/services/bls_aggregation/blsagg.go#L263))
and the return condition is: 
- return whenever min threshold met
- if threshold hasnt been met after n seconds, return an err

**Describe the solution you'd like**

AVSs that want low latency (at the cost of potential gas costs) need a more flexible API, in the form of:
- minimum signed stake threshold
- max # blocks of latency
- num blocks to expiry
with return condition being:
- as soon as min signed stake threshold is met, return if max # blocks of latency have expired, otherwise keep aggregating for that many blocks. (this way can keep aggregating to reduce gas costs, but with a max # blocks of latency SLA)
- if # blocks to expiry is met, return err

**Describe alternatives you've considered**

Mauro and Mariano, would this interface work for AlignedLayer?

**Comment by MauroToscano** [comment]
This would work. Thanks @samlaf. It could be max blocks or max time, whatever is easier to implement. If it's a block we would use it in 1 probably. Signatures are collected really fast, so waiting just 1 extra second would be enough.

**Comment by MauroToscano** [comment]
I'm adding some costs to have as data points, we collected using Aligned with different proportions of stake and amount of operators.

If you assume a uniform distribution of stake, the gas cost of the verification is this one:

![Respond to Task costs, 2_3 of stake required, uniform distribution of stake](https://github.com/user-attachments/assets/5dae94e6-1a37-4b58-bc5c-a1eab026a755)

In reality, it's a paretto, that in the worst case, when only the biggest signers signatures are aggregated, works like this:

![Respond to Task costs, 2_3 of stake required, Pareto distribution of stake (worst scenario)](https://github.com/user-attachments/assets/85e32d5d-9060-4bb6-91c9-251a137e2bc7)

As it can be seen, what should cost 280k quickly costs more than 1M.

In Aligned Testnet, numbers are in the middle of both cases, closer to Paretto worst case than the uniform case.

With the solution of waiting for more signature, costs should be 280k for all cases

**Comment by MauroToscano** [comment]
Also, just in case, title of the issue is misleading, since it doesn't matter if it's block or time based, but description is fine!
