### ISSUE TITLE
The `eigen_rpc_request_duration_seconds` need change `_seconds` suffix of the metric name

### ISSUE THREAD

**Issue by fyInALT** [Layr-Labs/eigensdk-go#333]
**Describe the bug**

Noticed that the `eigen_rpc_request_duration_seconds` histogram metric seems to record abnormal values - it looks like they are expressed in nanoseconds which contradicts the `_second` suffix of the metric name

**Expected behavior**

For this request duration, we need change it 's name.

**Screenshots**

**OS details**

**Additional context**

**Comment by samlaf** [comment]
I’d prefer to change the behavior and fix it to export seconds instead.
