### ISSUE TITLE
Update operator metadata validation

### ISSUE THREAD

**Issue by shrimalmadhur** [Layr-Labs/eigensdk-go#34]
**Is your feature request related to a problem? Please describe.**

We want to update the operator metadata validation - https://github.com/Layr-Labs/eigensdk-go/blob/master/types/operator_metadata.go#L38

**Describe the solution you'd like**

- Logo image should be a square
- Only support `svg/png/jpg/webp`
- 200 char on name

**Describe alternatives you've considered**

**Additional context**

**Comment by samlaf** [comment]
@shrimalmadhur you've improved this a lot lately for mainnet. Can we close it?

**Comment by samlaf** [comment]
Done. Work split over multiple PRs.
