### ISSUE TITLE
Bug: Issue when RPC does not support optional method eth_maxPriorityFeePerGas

### ISSUE THREAD

**Issue by dmanc** [Layr-Labs/eigensdk-go#46]
**Describe the bug**

Got the following log when attempting to register an operator:
```
2023-10-19T00:43:23.109Z        INFO    logging/zap_logger.go:89        registering operator 0xa306ac142eedc7bb636e6fd32d967e971ed986e3 to EigenLayer
2023/10/19 00:43:25 unsupported method: eth_maxPriorityFeePerGas
```

Seems to be an issue when RPC does not support eth_maxPriorityFeePerGas. Need a fallback mechanism, here is how EigenDA does it https://github.com/Layr-Labs/eigenda/blob/d4204a81e5bc98077d676fdce723f777e860f08e/common/geth/client.go#L108.

**To Reproduce**

Followed the registration flow and ran
```
eigenlayer operator register operator-config.yaml
```

**Expected behavior**

Should successfully register operator.

**Screenshots**

**OS details**

**Additional context**

**Comment by samlaf** [comment]
Which rpc endpoint were you using? Do we know when this call is not supported? Is it infura/alchemy blocking it?

**Comment by dmanc** [comment]
Spice endpoint. Infura worked for me.

**Comment by samlaf** [comment]
Been a while, but I believe this is now fixed by https://github.com/Layr-Labs/eigensdk-go/blob/master/chainio/txmgr/txmgr.go#L164 (very similar code to what eigenda is doing afaict).

Will close. Can reopen if this still happens.
