### ISSUE TITLE
Separate errors in errors.go

### ISSUE THREAD

**Issue by shrimalmadhur** [Layr-Labs/eigensdk-go#7]
**Is your feature request related to a problem? Please describe.**
Have Errors in errors.go file so they are easily identifiable and exportable and useable by client

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by korayakpinar** [comment]
Can anyone give some context about it cause it looked to me that they are actually separate, should we build our own type abstraction for errors or something like that?

**Comment by samlaf** [comment]
@shrimalmadhur this is probably just an old issue that needs to be closed right? Seems like we have errors in https://github.com/Layr-Labs/eigensdk-go/blob/master/types/errors.go now

**Comment by samlaf** [comment]
Closing as we have errors.go.
